### ISSUE TITLE
Sounds aren't playing

### ISSUE THREAD

**Issue by kus** [Kandru/cs2-quake-sounds#1]
Thank you for this plugin, but sounds aren't playing for me.

The plugin is loading correctly:

```
17:24:51 [INFO] (cssharp:PluginContext) Loading plugin QuakeSounds
[QuakeSounds] Configuration loaded
17:24:51 [INFO] (cssharp:PluginContext) Finished loading plugin CS2 QuakeSounds
```

When I joined the server it prompted me to download the Quake Sounds Pack which I allowed.

```
[MultiAddonManager] Steam API Activated
[MultiAddonManager] Refreshing addons to check for updates
[MultiAddonManager] Refreshing addons (3461824328)
[MultiAddonManager] Adding search path: D:\git\cs2-modded-server\server\game\bin\win64\steamapps/workshop/content/730/3461824328/3461824328.vpk
[MultiAddonManager] Hook_HostStateRequest: setting addon string to "3461824328"
```

The plugin loads properly and shows this in the logs, but I don't hear any sound:

```
[QuakeSounds][DEBUG]: Player Kus has 3 kills.
[QuakeSounds][DEBUG]: Playing quake sound QuakeSoundsD.Triplekill for player Kus.
[QuakeSounds][DEBUG]: Playing quake sound on player.
```

My config:

```
{
    "enabled": true,
    "debug": true,
    "play_on": "player",
    "ignore_bots": true,
    "enable_center_message": true,
    "center_message_type": "default",
    "enable_chat_message": true,
    "count_self_kills": false,
    "count_team_kills": false,
    "reset_kills_on_death": true,
    "reset_kills_on_round_start": false,
    "sounds": {
        "3": {
            "de": "Dreifach-Kill",
            "en": "Triple Kill",
            "_sound": "QuakeSoundsD.Triplekill"
        },
        "5": {
            "de": "Multi-Kill",
            "en": "Multi Kill",
            "_sound": "QuakeSoundsD.Multikill"
        },
        "6": {
            "de": "Randale",
            "en": "Rampage",
            "_sound": "QuakeSoundsD.Rampage"
        },
        "7": {
            "de": "Abschuss-Serie",
            "en": "Killing Spree",
            "_sound": "QuakeSoundsD.Killingspree"
        },
        "8": {
            "de": "Dominierend",
            "en": "Dominating",
            "_sound": "QuakeSoundsD.Dominating"
        },
        "9": {
            "de": "Beeindruckend",
            "en": "Impressive",
            "_sound": "QuakeSoundsD.Impressive"
        },
        "10": {
            "de": "Unstoppbar",
            "en": "Unstoppable",
            "_sound": "QuakeSoundsD.Unstoppable"
        },
        "knifekill": {
            "de": "Messer-Kill",
            "en": "Knife Kill",
            "_sound": "QuakeSoundsD.Haha"
        },
        "teamkill": {
            "de": "Team-Kill",
            "en": "Team Kill",
            "_sound": "QuakeSoundsD.Teamkiller"
        },
        "selfkill": {
            "de": "Selbsttötung",
            "en": "Self Kill",
            "_sound": "QuakeSoundsD.Perfect"
        }
    },
    "player_muted": [
        "[U:1:XXXX]"
    ],
    "player_languages": {
        "[U:1:XXXX]": "de"
    },
    "ConfigVersion": 1
}
```

I added this in:

```
    "player_muted": [
        "[U:1:XXXX]"
    ],
    "player_languages": {
        "[U:1:XXXX]": "de"
    },
```

Because when I had:

```
    "player_muted": [],
    "player_languages": {},
```

I got this error (which is `if (!Config.PlayerLanguages.ContainsKey(steamID)`):

```
17:05:43 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at QuakeSounds.QuakeSounds.LoadPlayerLanguage(String steamID) in /home/runner/work/cs2-quake-sounds/cs2-quake-sounds/src/Config.cs:line 78
   at QuakeSounds.QuakeSounds.OnPlayerConnect(EventPlayerConnectFull event, GameEventInfo info) in /home/runner/work/cs2-quake-sounds/cs2-quake-sounds/src/QuakeSounds.cs:line 129
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

```
] css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 13 plugins loaded.
  [#1:LOADED]: "Custom Votes" (1.1.3) by imi-tat0r
    Allows you to create custom votes for your server.
  [#2:LOADED]: "CS2 Announcement Broadcaster" (0.5.0) by Lengran
    A plugin that helps server admins to broadcast announcements to users. https://github.com/lengran/CS2AnnouncementBroadcaster
  [#3:LOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl
    Allows for server commands to be executed from the client using !rcon
  [#4:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus)
    Executes a command after server event or a delay. exec_after for help
  [#5:LOADED]: "FixRandomSpawn" (1.1.4) by xstage
  [#6:LOADED]: "GameModeManager" (1.0.56) by Striker-Nick
    A simple plugin to help administrators manage custom game modes, settings, and map rotations.
  [#7:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory
    Allow server owners to easily create unique configuration files on a per map basis.
  [#8:LOADED]: "SimpleAdmin" (0.1.2)
  [#9:LOADED]: "WASDMenuAPI" (1.0.5) by Interesting
  [#10:LOADED]: "CS2_GunGame" (v1.1.2) by Sergey
    GunGame mode for CS2
  [#11:LOADED]: "Remove Map Weapons" (1.0.1) by Kus (https://github.com/kus)
    Remove the weapons from the map
  [#12:LOADED]: "MutualScoringPlayers" (1.0.1) by xstage
  [#13:LOADED]: "CS2 QuakeSounds" (1.0.1) by Kalle <kalle@kandru.de>
```

```
] meta list
Listing 5 plugins:
  [01] CounterStrikeSharp (v1.0.316 @ 0d23387) by Roflmuffin
  [02] Rampbugfix (2024-11-06-0-ge79d9ee) by xen, Poggu, and the Source2ZE community (reduced by interesting with rampfix by zer0)
  [03] Movement Unlocker (1.4) by Vauff
  [04] MultiAddonManager (v1.3.5-0-ge883513) by xen
  [05] ServerListPlayersFix (1.0.1) by Poggu
```

Would you also be able to add `headshot` as a sound so we can have a sound play when you get a headshot (like the old 1.6 quake mod).

**Comment by derkalle4** [comment]
Hi @kus thanks for your feedback. Seems like I haven't tested these conditions. Will fix that later on :) 

What sound should the headshot sound be? Have you got a link to the sourcemod plugin or any other site?

I will add a headshot sound and code for this, sure :) good finding!

**Comment by derkalle4** [comment]
Just for clarification: you not only downloaded the Workshop Addon via the CS2 server but also on your client, correct?

**Comment by derkalle4** [comment]
Sorry, ignore my posts. Bug is fixed (was late last night so I missed an easy compiler warning :D). Also added "headshot". Updated README accordingly. Thanks for your feedback @kus

**Comment by kus** [comment]
Updated to `1.0.5`

```
css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 13 plugins loaded.
  [#1:LOADED]: "Custom Votes" (1.1.3) by imi-tat0r
    Allows you to create custom votes for your server.
  [#2:LOADED]: "CS2 Announcement Broadcaster" (0.5.0) by Lengran
    A plugin that helps server admins to broadcast announcements to users. https://github.com/lengran/CS2AnnouncementBroadcaster
  [#3:LOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl
    Allows for server commands to be executed from the client using !rcon
  [#4:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus)
    Executes a command after server event or a delay. exec_after for help
  [#5:LOADED]: "FixRandomSpawn" (1.1.4) by xstage
  [#6:LOADED]: "GameModeManager" (1.0.56) by Striker-Nick
    A simple plugin to help administrators manage custom game modes, settings, and map rotations.
  [#7:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory
    Allow server owners to easily create unique configuration files on a per map basis.
  [#8:LOADED]: "SimpleAdmin" (0.1.2)
  [#9:LOADED]: "WASDMenuAPI" (1.0.5) by Interesting
  [#10:LOADED]: "CS2_GunGame" (v1.1.2) by Sergey
    GunGame mode for CS2
  [#11:LOADED]: "Remove Map Weapons" (1.0.1) by Kus (https://github.com/kus)
    Remove the weapons from the map
  [#12:LOADED]: "MutualScoringPlayers" (1.0.1) by xstage
  [#13:LOADED]: "CS2 QuakeSounds" (1.0.5) by Kalle <kalle@kandru.de>
```

I still don't hear anything.

```
[QuakeSounds][DEBUG]: Player Kus killed by Delrow with weapon m249.
[QuakeSounds][DEBUG]: Player Kus has 3 kills.
[QuakeSounds][DEBUG]: Playing quake sound QuakeSoundsD.Triplekill for player Kus.
[QuakeSounds][DEBUG]: Playing quake sound on player.
```

Still seeing this in the console:

```
18:42:21 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at QuakeSounds.QuakeSounds.LoadPlayerLanguage(String steamID) in /home/runner/work/cs2-quake-sounds/cs2-quake-sounds/src/Config.cs:line 82
   at QuakeSounds.QuakeSounds.OnPlayerConnect(EventPlayerConnectFull event, GameEventInfo info) in /home/runner/work/cs2-quake-sounds/cs2-quake-sounds/src/QuakeSounds.cs:line 160
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

This is my config now:

```
{
    "enabled": true,
    "debug": true,
    "play_on": "player",
    "ignore_bots": true,
    "enable_center_message": true,
    "center_message_type": "default",
    "enable_chat_message": true,
    "count_self_kills": false,
    "count_team_kills": false,
    "reset_kills_on_death": true,
    "reset_kills_on_round_start": false,
    "sounds": {
        "3": {
            "de": "Dreifach-Kill",
            "en": "Triple Kill",
            "_sound": "QuakeSoundsD.Triplekill"
        },
        "5": {
            "de": "Multi-Kill",
            "en": "Multi Kill",
            "_sound": "QuakeSoundsD.Multikill"
        },
        "6": {
            "de": "Randale",
            "en": "Rampage",
            "_sound": "QuakeSoundsD.Rampage"
        },
        "7": {
            "de": "Abschuss-Serie",
            "en": "Killing Spree",
            "_sound": "QuakeSoundsD.Killingspree"
        },
        "8": {
            "de": "Dominierend",
            "en": "Dominating",
            "_sound": "QuakeSoundsD.Dominating"
        },
        "9": {
            "de": "Beeindruckend",
            "en": "Impressive",
            "_sound": "QuakeSoundsD.Impressive"
        },
        "10": {
            "de": "Unstoppbar",
            "en": "Unstoppable",
            "_sound": "QuakeSoundsD.Unstoppable"
        },
        "knifekill": {
            "de": "Messer-Kill",
            "en": "Knife Kill",
            "_sound": "QuakeSoundsD.Haha"
        },
        "teamkill": {
            "de": "Team-Kill",
            "en": "Team Kill",
            "_sound": "QuakeSoundsD.Teamkiller"
        },
        "selfkill": {
            "de": "Selbsttötung",
            "en": "Self Kill",
            "_sound": "QuakeSoundsD.Perfect"
        },
        "headshot": {
            "de": "Kopfschuss",
            "en": "Headshot",
            "_sound": "QuakeSoundsD.Headshot"
        },
        "weapon_hegrenade": {
            "de": "Granaten-Kill",
            "en": "Grenade Kill",
            "_sound": "QuakeSoundsD.Perfect"
        }
    },
    "player_muted": [
        "[U:1:XXXX]"
    ],
    "player_languages": {
        "[U:1:XXXX]": "de"
    },
    "ConfigVersion": 1
}
```

**Comment by derkalle4** [comment]
@kus rolled out a quick fix: simply ignoring the fact that your server does not have valid steam ids, thus not saving or loading the players language.

**Comment by kus** [comment]
As you know I run the [modded server over here](https://github.com/kus/cs2-modded-server).

I test plugins first on my Windows gaming PC, the server is setup as an internet server with Steam Web API key and Game server login token.

Have you tested it on Windows?

I had this set:

```
    "player_muted": [],
    "player_languages": {},
```

But was causing this error:

```
17:05:43 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at QuakeSounds.QuakeSounds.LoadPlayerLanguage(String steamID) in /home/runner/work/cs2-quake-sounds/cs2-quake-sounds/src/Config.cs:line 78
   at QuakeSounds.QuakeSounds.OnPlayerConnect(EventPlayerConnectFull event, GameEventInfo info) in /home/runner/work/cs2-quake-sounds/cs2-quake-sounds/src/QuakeSounds.cs:line 129
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by derkalle4** [comment]
@kus yeah developing on Windows and running production on Linux. The error you mention is when the NetworkIDString is empty. It is not related to the configuration. I don't know why it is empty on your server. However, the latest version should fix this. Do you have the latest CounterstrikeSharp with latest Runtime?

**Comment by kus** [comment]
@derkalle4 thanks for all your updates.

I'm so sorry, it turns out the problem was with the [GunGame plugin](https://github.com/ssypchenko/cs2-gungame) I was using, it was the mode I wanted the sounds on and only tested on that. I added it to other game modes and it worked as expected.

Do you have any idea why that plugin stops your sounds from playing?

**Comment by derkalle4** [comment]
@kus no idea and I do not have time to debug for you. Maybe the GunGame plugin is somehow stopping the EventPlayerDeath under some circumstances or does reset the EmitSound functions. You can enable debug mode in my plugin and you should see some debug lines when you frag someone. If these debug lines still state that a sound should get played but you cannot hear them or if you do not see debug lines as soon as the GunGame plugin got enabled it's at least one clue and would be something for that author.

I only do very basic stuff in this plug-in but plug-ins can do crazy stuff which impact other plug-ins. Sadly I cannot fix something on my end I guess.
